# Generated by Django 3.0.6 on 2020-05-25 06:40

from django.db import migrations

FOOD_TYPES = ['Corn', 'Wheat', 'Barley', 'Oats', 'Rice', 'Birdseed', 'Graps', 'Nuts', 'Frozen Peas', 'Earthworms', 'Mealworms', 'Lettuce', 'Other']


def add_food_types(apps, schema_editor):
    FoodType = apps.get_model('duckevents', 'FoodType')
    FoodType.objects.bulk_create(FoodType(name=n) for n in FOOD_TYPES)


class Migration(migrations.Migration):

    dependencies = [
        ('duckevents', '0002_add_countries'),
    ]

    operations = [
        migrations.RunPython(add_food_types)
    ]
