# Generated by Django 3.0.6 on 2020-05-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duckevents', '0004_auto_20200525_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='feedentry',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='duckevents.FeedSchedule'),
        ),
    ]
